version: "3"

services:
  db:
    image: "postgres:13-alpine"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432 
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db_data/:/var/lib/postgresql/data/
    networks:
      - api_network
    restart: always

  web:
    build: ./api/.
    env_file:
      - .env
    command: bash -c "alembic upgrade head && python main.py"
    volumes:
      - .:/app    
    depends_on:
      - db
    networks:
      - api_network
    restart: always

  server:
    build: ./server/.
    volumes:
      - ./server/html_files/:/usr/share/nginx/html
    depends_on:
      - db
      - web
    networks:
      - api_network
    ports:
      - ${PORT}:80
    restart: always

networks:
  api_network:
    driver: bridge
